// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyuazarxoiyvtihscwwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5dWF6YXJ4b2l5dnRpaHNjd3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODYzOTksImV4cCI6MjA2MTY2MjM5OX0.O5eyAo5Eq6xNa45tNht5lq6IQ6s4YKwSGhQteOdgWD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);